-- Item 16 (Option B) — Project-Scoped Candidate Profile Authority.
--
-- Lock FIRST, before any DDL, so the migration never holds a lock of its
-- own while it is still waiting on an in-flight CandidateProjectLink
-- creation transaction (ratified lock-order correction). SHARE conflicts
-- with ROW EXCLUSIVE (what a plain INSERT acquires) but not with ACCESS
-- SHARE (plain SELECT), so concurrent reads of CandidateProjectLink are
-- unaffected; only new writes to it are blocked until this migration
-- commits. Released automatically at COMMIT — not a permanent lock.
LOCK TABLE "CandidateProjectLink" IN SHARE MODE;

-- CreateTable
CREATE TABLE "CandidateProjectAuthority" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "currentDocumentId" TEXT,
    "currentUploadedAt" TIMESTAMP(3),
    "currentProcessingRunId" TEXT,
    "currentAttemptNumber" INTEGER,

    CONSTRAINT "CandidateProjectAuthority_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CandidateProjectAuthority_candidateId_projectId_key" ON "CandidateProjectAuthority"("candidateId", "projectId");

-- AddForeignKey
ALTER TABLE "CandidateProjectAuthority" ADD CONSTRAINT "CandidateProjectAuthority_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CandidateProjectAuthority" ADD CONSTRAINT "CandidateProjectAuthority_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "RecruitmentProject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CandidateProjectAuthority" ADD CONSTRAINT "CandidateProjectAuthority_currentDocumentId_fkey" FOREIGN KEY ("currentDocumentId") REFERENCES "CandidateDocument"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CandidateProjectAuthority" ADD CONSTRAINT "CandidateProjectAuthority_currentProcessingRunId_fkey" FOREIGN KEY ("currentProcessingRunId") REFERENCES "ProcessingRun"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Backfill (Item 16B, ratified reconstruction algorithm) — this is a
-- reconstruction of the new project-scoped authority state as if it had
-- existed all along, NOT a claim about historical project-authority facts
-- (no such concept existed before this migration). One row per existing
-- CandidateProjectLink; the protective lock above guarantees every link
-- that existed, or whose creating transaction had already committed, when
-- the lock was acquired is included here. Plain INSERT, no ON CONFLICT —
-- a duplicate (candidateId, projectId) is an invariant violation and must
-- fail this migration loudly rather than being silently absorbed.
-- gen_random_uuid() here is a migration-only mechanism for generating this
-- backfill's row ids; it is not an application-level id-generation
-- convention (every other row in this schema has its id generated by
-- Prisma Client, never by the database).
INSERT INTO "CandidateProjectAuthority"
  ("id", "candidateId", "projectId", "currentDocumentId", "currentUploadedAt", "currentProcessingRunId", "currentAttemptNumber")
SELECT
  gen_random_uuid(),
  link."candidateId",
  link."projectId",
  winner.document_id,
  winner.uploaded_at,
  winner.run_id,
  winner.attempt_number
FROM "CandidateProjectLink" link
LEFT JOIN LATERAL (
  SELECT cd."id" AS document_id, cd."uploadedAt" AS uploaded_at, pr."id" AS run_id, pr."attemptNumber" AS attempt_number
  FROM "CandidateDocument" cd
  JOIN "ProcessingRun" pr ON pr."candidateDocumentId" = cd."id"
  WHERE cd."candidateId" = link."candidateId"
    AND cd."projectId" = link."projectId"
    AND pr."status" = 'COMPLETED'
  ORDER BY cd."uploadedAt" DESC, cd."id" DESC, pr."attemptNumber" DESC
  LIMIT 1
) winner ON true;
